sonar.projectKey=epic-vitals
sonar.projectName=epic-vitals
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.branch.name=main
sonar.qualitygate.wait=true
sonar.host.url=${SONARQUBE_HOST_URL}
sonar.scm.provider=git
